name: dashclicker
description: A codelab for in-app purchases
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.5
  cloud_functions: ^3.2.4
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.4
  firebase_core: ^1.10.6
  flutter:
    sdk: flutter
  google_sign_in: ^5.2.1
  in_app_purchase: ^2.0.1
  intl: ^0.17.0
  provider: ^6.0.2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
